[package]
name = "justice_hash_rough"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.4.0"
serde_json = "1.0.91"
tiny-keccak = { version = "2.0.2", features = ["k12"] }
