[package]
name = "ipfs-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.20", features = ["csr"] }
gloo-net = "0.2.6"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"
yaml-rust = "0.4.5"
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1", features = ["rt"] }
serde_json = "1.0.95"
base64 = "0.21.0"
