[package]
name = "justice_hash_rough"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10.6"
yaml-rust = "0.4.5"

yew = { version = "0.20.0", features = ["csr"] }
